### ISSUE TITLE
Crash with new forge?

### ISSUE THREAD

**Issue by jjc54** [enhancedportals/enhancedportals#1]
Getting this start-up crash with:
Enhanced Portals 3: EnhancedPortals_1.7.10-universal-3.0.11
Forge: 1.7.10-Forge10.13.4.1445-1.7.10

Crash Report: http://pastebin.com/HE8iJszw

**Comment by steelshot** [comment]
iam getting this too, its not forge, clearly says "Invalid shaped ore recipe" and mentions TE.

**Comment by Alz454** [comment]
I messed up with the TE recipes, I'll have a fixed version up later but for now you can fix this by disabling the TE recipes in the config file.

**Comment by Alz454** [comment]
Fixed in: 75771a17f41aff208ec3ae3d4ce2db1232a719ad
